### ISSUE TITLE
read your feedbacks

### ISSUE THREAD

**Issue by PortableGames** [nebuIr/Default-Dark-Mode#100]
### Description

https://feedback.darkomizer.com/posts/2/possibility-to-change-the-colour-of-the-item-selection-and-the-colour-of-the-menu-button

### Link to the mod page

https://feedback.darkomizer.com/posts/2/possibility-to-change-the-colour-of-the-item-selection-and-the-colour-of-the-menu-button

### Game versions

1.19

### Modloaders

Other

**Comment by nebuIr** [comment]
Thanks for your suggestion!

I have it on my to-do list for possible future features 😄
