### ISSUE TITLE
[Mod Support Request] Useful Backpacks

### ISSUE THREAD

**Issue by DTX3** [nebuIr/Default-Dark-Mode#101]
### Description

Request for Dark UI for the mod Useful Backpacks.

It has 3 types of view, small, medium and large.

### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/useful-backpacks

### Game versions

1.19, 1.18

### Modloaders

Forge

**Comment by nebuIr** [comment]
Support added for 1.20, 1.19 & 1.18
