### ISSUE TITLE
[Mod Support Request] EMI UPDATE

### ISSUE THREAD

**Issue by CodeF53** [nebuIr/Default-Dark-Mode#102]
### Description

EMI updated its `src/main/resources/assets/emi/textures/gui/background.png`, leading to the left tab texture being used in the inside.

![image](https://user-images.githubusercontent.com/37855219/224462721-df8c950c-e710-445c-ab09-bfd8472c5fcf.png)

### Link to the mod page

https://modrinth.com/mod/emi

### Game versions

1.19, 1.18

### Modloaders

Fabric

**Comment by nebuIr** [comment]
Textures updated to latest version ✅
