### ISSUE TITLE
[Mod Support Request] Lovely Snails

### ISSUE THREAD

**Issue by MrDudeGuySirMan** [nebuIr/Default-Dark-Mode#103]
### Description

lamdaurora's mod Lovely Snails contains snails that, when grown up, can be fitted with multiple items. this snail GUI is custom. this texture pack is the best, thanks for all your hard work!

### Link to the mod page

https://modrinth.com/mod/lovely_snails

### Game versions

1.19

### Modloaders

Fabric, Quilt

**Comment by nebuIr** [comment]
Support for 1.20 & 1.19 added
