### ISSUE TITLE
[Mod Support Request] Simple Voice Chat

### ISSUE THREAD

**Issue by Greeenman999** [nebuIr/Default-Dark-Mode#105]
### Description

![Screenshot_20230319_145235](https://user-images.githubusercontent.com/81023792/226180704-eec1babf-321f-439a-99df-0f373c4426bc.png)
![Screenshot_20230319_145245](https://user-images.githubusercontent.com/81023792/226180706-77711efc-f829-4c5f-80e5-e0faf8b2a6cb.png)

### Link to the mod page

https://modrinth.com/plugin/simple-voice-chat

### Game versions

1.19

### Modloaders

Fabric

**Comment by nebuIr** [comment]
Support for 1.20, 1.19, 1.18 & 1.17 added
