### ISSUE TITLE
[Mod Support Request] Backpacked by MrCrayfish

### ISSUE THREAD

**Issue by TigerADPC** [nebuIr/Default-Dark-Mode#116]
### Description

A mod thats adds a backpack and cosmetic skins as rewards for challenges.
There are two menus to change: the backpack inventory, skin menu

### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/backpacked

### Game versions

1.19, 1.18

### Modloaders

Fabric, Forge

**Comment by nebuIr** [comment]
Support added ✅
