### ISSUE TITLE
[Missing textures] AE2 WIRELESS IS BUGGED

### ISSUE THREAD

**Issue by FearAK** [nebuIr/Default-Dark-Mode#120]
### Description

https://i.imgur.com/a04lYCR.png

![a04lYCR](https://github.com/nebuIr/Default-Dark-Mode/assets/20028702/066e69f1-df80-47c7-8c88-b5fe4339bfb0)

### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals

### Game versions

1.19

### Modloaders

Forge

**Comment by nebuIr** [comment]
I updated the AE2W textures, which has fixed the issue.
