### ISSUE TITLE
[Missing textures] Smithing Table in 1.20

### ISSUE THREAD

**Issue by SLinxTheFox** [nebuIr/Default-Dark-Mode#123]
### Description

Smithing table has new slots now. examples below

Without items in
https://i.imgur.com/tpKGbGO.png

With items in
https://i.imgur.com/50NR9jm.png

### Game versions

1.20

**Comment by nebuIr** [comment]
The latest version ([2023.6.0](https://github.com/nebuIr/Default-Dark-Mode/releases/tag/2023.6.0)) already includes support for the new smithing table. Do you have the latest version installed?

I am unable to replicate your problem, either with the most recent version:
![c8ad566d](https://github.com/nebuIr/Default-Dark-Mode/assets/20028702/ab999d3e-d7b9-4ff5-8a21-e856516f0e9b)

or when generated using [darkomizer.com](https://darkomizer.com):
![f6f4d75e](https://github.com/nebuIr/Default-Dark-Mode/assets/20028702/71a25bf7-ed80-4e9b-bc6e-5b58a7d74883)
