### ISSUE TITLE
[Missing textures] Hotbar

### ISSUE THREAD

**Issue by xXnekit101Xx** [nebuIr/Default-Dark-Mode#136]
### Description

Hello, I would like you to add support for a dark theme in the HotBar - above the inventory which. And then it's standard as from a regular Minecraft. Please fix it!
![image](https://github.com/nebuIr/Default-Dark-Mode/assets/86162017/04e47732-7492-47f3-b1a4-f2ab1f8051cd)

### Game versions

1.19

**Comment by nebuIr** [comment]
As of version [2023.6.0](https://github.com/nebuIr/Default-Dark-Mode/releases/tag/2023.6.0) the hotbar is darker, including the currently selected slot.

Are you using at least version 2023.6.0?
