### ISSUE TITLE
[Missing textures] Failure to respect 1.20.2 changes to resource packs

### ISSUE THREAD

**Issue by DreamSt4n** [nebuIr/Default-Dark-Mode#138]
### Description

23w31a changed how several textures work, breaking UI on texture packs that weren't made for the update.

### Game versions

1.20

**Comment by DreamSt4n** [comment]
Is there any updates on this? I'm sure this is probably a hard task, but I was just wondering.

**Comment by nebuIr** [comment]
I'm currently working on it. It will be ready in time when 1.20.2 releases.
I might release a snapshot version beforehand.

**Comment by DreamSt4n** [comment]
Okay, thank you!

**Comment by nebuIr** [comment]
Support for 1.20.2 is now added in [2023.9.0](https://github.com/nebuIr/Default-Dark-Mode/releases/tag/2023.9.0)

**Comment by DreamSt4n** [comment]
This is still an issue. Please reopen.

**Comment by nebuIr** [comment]
Everything should be working. What issues do you have?

**Comment by DreamSt4n** [comment]
Using 2023.9.0 still has the issues present before the update. I can attach screenshots if necessary.

**Comment by DreamSt4n** [comment]
Both screenshots are using the same resource pack. (2023.9.0)

![1.20.1](https://github.com/nebuIr/Default-Dark-Mode/assets/19875208/71a2f7be-b386-426e-ab1b-5387dad75639)

![1.20.2](https://github.com/nebuIr/Default-Dark-Mode/assets/19875208/e7b033f3-6871-4f9a-b609-f3afc930473f)
