### ISSUE TITLE
[Missing textures] TrashSlot still light (Fabric version at least)

### ISSUE THREAD

**Issue by Fl414r** [nebuIr/Default-Dark-Mode#143]
### Description

![Снимок экрана (90)](https://github.com/nebuIr/Default-Dark-Mode/assets/74704475/412081af-287f-48b9-b765-b073d7e7a0b5)
![Снимок экрана (93)](https://github.com/nebuIr/Default-Dark-Mode/assets/74704475/ee6b09ac-ae66-4b8f-b766-69c84b821ac7)

### Game versions

1.20, 1.19

### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/trashslot

**Comment by nebuIr** [comment]
The slot item texture path changed, so that wasn't correct anymore.
But the container is still dark and works for me on 1.19.4 & 1.20.1.

What versions are you using?

**Comment by Fl414r** [comment]
> The slot item texture path changed, so that wasn't correct anymore.
> But the container is still dark and works for me on 1.19.4 & 1.20.1.
> 
> What versions are you using?

Oh, I literally forgot about this ~~post~~ issue
I just dumb and forgot that fabric resource pack set as first to load.
