### ISSUE TITLE
Add Support for following mods

### ISSUE THREAD

**Issue by itsdinkd** [nebuIr/Default-Dark-Mode#2]
[1.17.1 Fabric]
Tech Reborn
Industrial Revolution
Expanded Storage
Adorn
Farmers Delight
Tom's Simple Storage
Upgraded Shulkers

**Comment by nebuIr** [comment]
[Adorn](https://www.curseforge.com/minecraft/mc-mods/adorn) support added in #72

**Comment by nebuIr** [comment]
Support for [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn) & [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution) is still missing.
Every other mod is now supported. See [Mod support](https://github.com/nebuIr/Default-Dark-Mode/wiki/Mod-support) for reference.

Tech Reborn now has a dedicated issue at #124.

I'm closing this issue for better clarity. If you still wish to have support for Industrial Revolution, please feel free to create a new separate issue.
