### ISSUE TITLE
[Mod Support Request] EXAMPLE MOD

### ISSUE THREAD

**Issue by QuentinBAUDRY** [nebuIr/Default-Dark-Mode#210]
### Description

Hello,
 I am currently creating a mod pack that I want to publish on Modrinth but I am asked for authorization from you to publish my modpack with your mods.

Why am I doing this?

> I wanted to pre-install and put your packs in the right order so that players are a turnkey solution.

I have no ambition to monetize this project.
Sincerely 

### Link to the mod page

https://darkomizer.com/

### Game versions

1.20

### Mod Loaders

Fabric

**Comment by nebuIr** [comment]
Yes, you have my permission 🙂
