### ISSUE TITLE
[Mod Support Request] Applied Energistics 2 Wireless Terminals

### ISSUE THREAD

**Issue by uselessSABOTAGE** [nebuIr/Default-Dark-Mode#39]
### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals

### Game versions

1.18

### Modloaders

Fabric

### Description

Would you please add support for the Applied Energistics 2 add-on mod Wireless Terminals? Thanks!

**Comment by nebuIr** [comment]
Support added for 1.18 & 1.19 ✅

Applied Energetics 2 support (#36) still needs to be added to make everything look right.

**Comment by uselessSABOTAGE** [comment]
Thanks!
