### ISSUE TITLE
[Mod Support Request] AE2 Things

### ISSUE THREAD

**Issue by uselessSABOTAGE** [nebuIr/Default-Dark-Mode#40]
### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/ae2things

### Game versions

1.18

### Modloaders

Fabric

### Description

Would you please add support for the Applied Energistics 2 add-on mod AE2 Things? Thanks!

**Comment by arichorn** [comment]
Alright. I’m helping Neblur with these so I’ll make the textures and send them to neblur when finished

**Comment by arichorn** [comment]
finished! took an hour to make and add the only texture in it

**Comment by uselessSABOTAGE** [comment]
Thanks for your help!

**Comment by arichorn** [comment]
no problem!
your request is in here now :D
https://github.com/nebuIr/Default-Dark-Mode/pull/44

**Comment by nebuIr** [comment]
Thank you for your help! Pull request merged 👍
