### ISSUE TITLE
[Mod Support Request] Roughly Enough Items

### ISSUE THREAD

**Issue by uselessSABOTAGE** [nebuIr/Default-Dark-Mode#42]
### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items

### Game versions

1.19, 1.18

### Modloaders

Fabric

### Description

Would you please add support for Roughly Enough Items? Thanks!

**Comment by ryanccn** [comment]
Roughly Enough Items has built in dark mode, you just have to enable it in the settings.

**Comment by uselessSABOTAGE** [comment]
You're correct, however, dark modes aren't all the same.  I would like a cohesive look and feel across all of the GUIs.  You can see what I mean in the screenshots below. 

![2022-09-10_06 52 58](https://user-images.githubusercontent.com/100305564/189482119-990b2625-5b22-4f8f-93cc-8847f1eaac71.png)
![2022-09-10_06 52 44](https://user-images.githubusercontent.com/100305564/189482122-96b0802b-143d-4c05-ad6c-4274dcda2a08.png)

**Comment by ryanccn** [comment]
Ah, I see what you mean

**Comment by nebuIr** [comment]
Support for 1.19 & 1.18 added ✅

**Comment by ryanccn** [comment]
Thanks!
