### ISSUE TITLE
[Mod Support Request] TrashSlot Mod - Balm (Forge Edition)

### ISSUE THREAD

**Issue by arbaizamio** [nebuIr/Default-Dark-Mode#43]
### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/trashslot

### Game versions

1.19, 1.18, 1.17

### Modloaders

Other

### Description

I would like it to be compatible with the TrashSlot mod and its add-on Balm (Forge Edition)
https://www.curseforge.com/minecraft/mc-mods/trashslot
https://www.curseforge.com/minecraft/mc-mods/balm

**Comment by nebuIr** [comment]
Support added
