### ISSUE TITLE
[Mod Support Request] Easy Villagers

### ISSUE THREAD

**Issue by arbaizamio** [nebuIr/Default-Dark-Mode#45]
### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/easy-villagers

### Game versions

1.19, 1.18, 1.17

### Modloaders

Forge

### Description

hello, I would like it to be adapted with the interface of this mod, thank you very much, for what you do

**Comment by nebuIr** [comment]
Support added ✅
