### ISSUE TITLE
[Mod Support Request] Modmenu (Fabric)

### ISSUE THREAD

**Issue by notabirb1** [nebuIr/Default-Dark-Mode#47]
### Link to the mod page

https://modrinth.com/mod/modmenu

### Game versions

1.19, 1.18, 1.17, 1.16

### Modloaders

Fabric

### Description

While most of Modmenu uses the default button textures, there are some icons (Config, Mod Sorting, Alternate Modmenu Button, etc.) that use custom textures. Since this is a fairly popular mod for Fabric, it makes sense that it would be supported.

**Comment by nebuIr** [comment]
Support added
