### ISSUE TITLE
[Mod Support Request] EMI

### ISSUE THREAD

**Issue by ryanccn** [nebuIr/Default-Dark-Mode#51]
### Description

**EMI** is a featureful and accessible item and recipe viewer. It brings many new features, and optimizes for the user experience. Outside of the standard Fabric/Quilt API, EMI requires zero dependencies, and can be launched with the game simply and easily.

### Link to the mod page

https://modrinth.com/mod/emi

### Game versions

1.19, 1.18

### Modloaders

Fabric, Quilt

**Comment by ryanccn** [comment]
Textures that need to be patched are mainly in [`src/main/resources/assets/emi/textures/gui`](https://github.com/emilyploszaj/emi/tree/main/src/main/resources/assets/emi/textures/gui).

**Comment by nebuIr** [comment]
Support added ✅

**Comment by ryanccn** [comment]
Thanks!
