### ISSUE TITLE
[Mod Support Request] Bedrockify

### ISSUE THREAD

**Issue by ryanccn** [nebuIr/Default-Dark-Mode#52]
### Description

BedrockIfy is a fabric Minecraft Mod that implements some useful Minecraft Bedrock Edition features into Minecraft Java Edition.

### Link to the mod page

https://modrinth.com/mod/bedrockify

### Game versions

1.19, 1.18, 1.17

### Modloaders

Fabric

**Comment by ryanccn** [comment]
Only GUI texture needed is this: https://github.com/juancarloscp52/BedrockIfy/blob/1.19/src/main/resources/assets/bedrockify/textures/gui/bedrockify_widgets.png

**Comment by nebuIr** [comment]
Support added ✅

**Comment by ryanccn** [comment]
tysm!
