### ISSUE TITLE
Darkomizer isn't Compatible with 22w45a Inventory Changes

### ISSUE THREAD

**Issue by DreamStanMan** [nebuIr/Default-Dark-Mode#59]
In 22w45a, the Creative Mode tabs were made slimmer with the addition of the Operator Blocks Tab, and this conflicts with current Darkomizer packs, showing an unused red "User" picture.

**Comment by nebuIr** [comment]
Thanks for bringing that up!
I added a `snapshot` option to the versions select field: https://darkomizer.com/
