### ISSUE TITLE
[Mod Support Request] Inventory Profiles Next

### ISSUE THREAD

**Issue by DarkkRevenant** [nebuIr/Default-Dark-Mode#82]
### Description

This mod adds some small buttons inside the crafting menu for sorting. It would be awesome if those buttons would take to the rest of the GUI.

### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next

### Game versions

1.19, 1.18, 1.16

### Modloaders

Fabric, Forge, Quilt

**Comment by nebuIr** [comment]
Support added for 1.20, 1.19, 1.18 & 1.16
