### ISSUE TITLE
[Mod Support Request] Sophisticated Backpacks

### ISSUE THREAD

**Issue by Alle-thebug** [nebuIr/Default-Dark-Mode#93]
### Link to the mod page

https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

### Game versions

1.18

### Modloaders

Forge

**Comment by LarveyOfficial** [comment]
+1 (1.19.2)

**Comment by nebuIr** [comment]
Support added for 1.20, 1.19 & 1.18
