### ISSUE TITLE
Slider GUI textures revert to default with current texture packs

### ISSUE THREAD

**Issue by DreamStanMan** [nebuIr/Default-Dark-Mode#98]
As of 23w03a, several GUI textures were modified to fix some small visual bugs. This must have caused the slider GUI textures to revert to the vanilla textures.

**Comment by nebuIr** [comment]
The [snapshot branch](https://github.com/nebuIr/Default-Dark-Mode/tree/snapshot) is now compatible with the latest snapshot [23w04a](https://www.minecraft.net/de-de/article/minecraft-snapshot-23w04a).
